server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb+srv://travishuy:travishuy@travishuy.2ak1k.mongodb.net/?retryWrites=true&w=majority&appName=travishuy
      database: travishuy
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope: user:email
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: restaurant-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
jwt:
  secret: dBF9k6ffpPKOgylzlE6vV9gzIJz7bVjbdF3L5G8zWxhT9kY2mN4qRcX7pS8wQ1aH3jK5nM9tR6vU4bX7cE0iY2wQ5sG8mP3fD4vJ7kL9nB2mX5tA
  expiration: 86400000  # 24 hours in milliseconds
  refreshExpiration: 604800000  # 7 days in milliseconds

vnpay:
  terminal-id: ${VNPAY_TERMINAL_ID}
  secret-key: ${VNPAY_SECRET_KEY}
  return-url: http://your-domain.com/api/payments/vnpay/callback
  api-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
